# Generated by Django 5.2.5 on 2026-02-27 15:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], default='student', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_users_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='labs_lab_name_25d20d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_code', models.CharField(help_text='Internal tracking ID (e.g., LAB1-SW-01)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human readable name (e.g., Cisco Core Switch)', max_length=200)),
                ('category', models.CharField(choices=[('INFRASTRUCTURE', 'Infrastructure'), ('APPLIANCE', 'Appliance')], default='INFRASTRUCTURE', max_length=20)),
                ('equipment_type', models.CharField(choices=[('SERVER', 'Server'), ('ROUTER', 'Router'), ('SWITCH', 'Switch'), ('HUB', 'Hub'), ('PROJECTOR', 'Projector'), ('E_BOARD', 'E-Board'), ('AC', 'Air Conditioner'), ('FAN', 'Fan'), ('LIGHT', 'Light'), ('UPS', 'UPS'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('working', 'Working'), ('not_working', 'Not Working'), ('under_repair', 'Under Repair')], default='working', max_length=20)),
                ('is_networked', models.BooleanField(default=False, help_text='Whether connected to network')),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('location_in_lab', models.CharField(blank=True, help_text='Wall A, Rack 2, Ceiling, etc.', max_length=200, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_equipments', to='labs.lab')),
            ],
            options={
                'ordering': ['equipment_code'],
            },
        ),
        migrations.CreateModel(
            name='ElectricalApplianceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_rating', models.CharField(blank=True, help_text='e.g., 1500W, 2HP', max_length=50, null=True)),
                ('voltage', models.CharField(blank=True, help_text='e.g., 220V, 110V', max_length=50, null=True)),
                ('inverter_type', models.BooleanField(default=False, help_text='Is it an inverter AC')),
                ('energy_rating', models.CharField(blank=True, help_text='e.g., 5 Star, A++', max_length=50, null=True)),
                ('service_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_details', to='labs.labequipment')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkEquipmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('rack_unit_size', models.PositiveIntegerField(blank=True, help_text='Size in rack units', null=True)),
                ('managed_switch', models.BooleanField(default=False, help_text='Is it a managed switch')),
                ('bandwidth_capacity', models.CharField(blank=True, help_text='e.g., 1Gbps, 10Gbps', max_length=50, null=True)),
                ('power_rating', models.CharField(blank=True, help_text='e.g., 500W', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_details', to='labs.labequipment')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text='Institution label for the PC', max_length=100)),
                ('product_id', models.CharField(blank=True, help_text='Manufacturer identifier', max_length=100, null=True)),
                ('processor', models.CharField(blank=True, help_text='Basic processor description', max_length=200, null=True)),
                ('ram', models.CharField(blank=True, help_text='e.g., 8GB', max_length=50, null=True)),
                ('storage', models.CharField(blank=True, help_text='e.g., 512GB SSD', max_length=50, null=True)),
                ('status', models.CharField(choices=[('working', 'Working'), ('not_working', 'Not Working')], default='working', max_length=20)),
                ('connected', models.BooleanField(default=True, help_text='Is the PC connected to network')),
                ('gpu', models.BooleanField(default=False, help_text='Dedicated GPU present')),
                ('peripherals', models.BooleanField(default=False, help_text='Peripherals tracked')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to='labs.lab')),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='OS name e.g., Windows, Ubuntu', max_length=100)),
                ('version', models.CharField(blank=True, help_text='OS version e.g., 11 Pro, 22.04', max_length=50, null=True)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='License expiration date', null=True)),
                ('architecture', models.CharField(choices=[('32-bit', '32-bit'), ('64-bit', '64-bit')], default='64-bit', max_length=20)),
                ('product_key', models.CharField(blank=True, help_text='License key', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='os', to='labs.pc')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='CPU model name', max_length=200)),
                ('clock_speed', models.CharField(blank=True, help_text='e.g., 3.6 GHz', max_length=50, null=True)),
                ('core_count', models.IntegerField(blank=True, help_text='Number of cores', null=True)),
                ('integrated_graphics', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='labs.pc')),
            ],
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peripheral_type', models.CharField(choices=[('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('headset', 'Headset'), ('webcam', 'Webcam'), ('printer', 'Printer'), ('speaker', 'Speaker'), ('other', 'Other')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('working', 'Working'), ('not_working', 'Not Working')], default='working', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peripheral_devices', to='labs.pc')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('status_before', models.CharField(blank=True, max_length=20, null=True)),
                ('status_after', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fixed', 'Fixed')], default='pending', max_length=20)),
                ('reported_on', models.DateTimeField(auto_now_add=True)),
                ('fixed_on', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_issues', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='labs.lab')),
                ('lab_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='labs.labequipment')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='labs.pc')),
                ('peripheral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='labs.peripheral')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(blank=True, help_text='e.g., 1920x1080, 4K', max_length=50, null=True)),
                ('brightness_lumens', models.PositiveIntegerField(blank=True, help_text='Brightness in lumens', null=True)),
                ('throw_type', models.CharField(blank=True, help_text='e.g., Short throw, Long throw', max_length=50, null=True)),
                ('hdmi_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projector_details', to='labs.labequipment')),
            ],
        ),
        migrations.CreateModel(
            name='ServerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_model', models.CharField(blank=True, max_length=200, null=True)),
                ('total_ram', models.CharField(blank=True, help_text='e.g., 32GB, 64GB', max_length=50, null=True)),
                ('total_storage', models.CharField(blank=True, help_text='e.g., 1TB SSD, 2x 500GB', max_length=50, null=True)),
                ('raid_config', models.CharField(blank=True, help_text='e.g., RAID 1, RAID 5', max_length=100, null=True)),
                ('virtualization_enabled', models.BooleanField(default=False)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='server_details', to='labs.labequipment')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('license_key', models.CharField(blank=True, max_length=200, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_software', to='labs.pc')),
            ],
        ),
        migrations.AddIndex(
            model_name='labequipment',
            index=models.Index(fields=['lab'], name='labs_labequ_lab_id_94342d_idx'),
        ),
        migrations.AddIndex(
            model_name='labequipment',
            index=models.Index(fields=['category'], name='labs_labequ_categor_e9b28d_idx'),
        ),
        migrations.AddIndex(
            model_name='labequipment',
            index=models.Index(fields=['equipment_type'], name='labs_labequ_equipme_c7c89f_idx'),
        ),
        migrations.AddIndex(
            model_name='labequipment',
            index=models.Index(fields=['status'], name='labs_labequ_status_f0f165_idx'),
        ),
        migrations.AddIndex(
            model_name='labequipment',
            index=models.Index(fields=['equipment_code'], name='labs_labequ_equipme_02d208_idx'),
        ),
        migrations.AddIndex(
            model_name='electricalappliancedetails',
            index=models.Index(fields=['equipment'], name='labs_electr_equipme_42c7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='networkequipmentdetails',
            index=models.Index(fields=['equipment'], name='labs_networ_equipme_c99f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='pc',
            index=models.Index(fields=['lab'], name='labs_pc_lab_id_ebf093_idx'),
        ),
        migrations.AddIndex(
            model_name='pc',
            index=models.Index(fields=['status'], name='labs_pc_status_e69197_idx'),
        ),
        migrations.AddIndex(
            model_name='pc',
            index=models.Index(fields=['device_name'], name='labs_pc_device__2c0aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='os',
            index=models.Index(fields=['pc'], name='labs_os_pc_id_17aa62_idx'),
        ),
        migrations.AddIndex(
            model_name='cpu',
            index=models.Index(fields=['pc'], name='labs_cpu_pc_id_e0f27b_idx'),
        ),
        migrations.AddIndex(
            model_name='peripheral',
            index=models.Index(fields=['pc'], name='labs_periph_pc_id_d303b4_idx'),
        ),
        migrations.AddIndex(
            model_name='peripheral',
            index=models.Index(fields=['peripheral_type'], name='labs_periph_periphe_736814_idx'),
        ),
        migrations.AddIndex(
            model_name='peripheral',
            index=models.Index(fields=['status'], name='labs_periph_status_95cabd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='peripheral',
            unique_together={('pc', 'peripheral_type', 'serial_number')},
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['pc'], name='labs_mainte_pc_id_831c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['lab_equipment'], name='labs_mainte_lab_equ_36a7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['peripheral'], name='labs_mainte_periphe_4fbcd2_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['lab'], name='labs_mainte_lab_id_4acc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['status'], name='labs_mainte_status_8f1180_idx'),
        ),
        migrations.AddIndex(
            model_name='projectordetails',
            index=models.Index(fields=['equipment'], name='labs_projec_equipme_ac2d10_idx'),
        ),
        migrations.AddIndex(
            model_name='serverdetails',
            index=models.Index(fields=['equipment'], name='labs_server_equipme_d54d15_idx'),
        ),
        migrations.AddIndex(
            model_name='software',
            index=models.Index(fields=['pc'], name='labs_softwa_pc_id_71d8a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='software',
            unique_together={('pc', 'name', 'version')},
        ),
    ]
