# Generated by Django 5.2.5 on 2026-02-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancelog',
            options={'ordering': ['-reported_on']},
        ),
        migrations.AlterModelOptions(
            name='pc',
            options={'ordering': ['device_name']},
        ),
        migrations.AlterModelOptions(
            name='peripheral',
            options={'ordering': ['pc', 'peripheral_type']},
        ),
        migrations.AlterUniqueTogether(
            name='peripheral',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='labequipment',
            name='equipment_code',
            field=models.CharField(help_text='Internal tracking ID (e.g., LAB1-SW-01)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='labequipment',
            unique_together={('lab', 'equipment_code')},
        ),
        migrations.AlterUniqueTogether(
            name='pc',
            unique_together={('lab', 'device_name')},
        ),
    ]
